### ISSUE TITLE
The UI is to small

### ISSUE THREAD

**Issue by Test123456789123456789Test** [MicroappsTeam/MAlone#1]
Here is some pictures show what I mean:
![Screenshot_2019-04-26-08-06-10-23](https://user-images.githubusercontent.com/50001414/56775614-6d046400-67fa-11e9-9a50-07416d2cceb6.png)
![Screenshot_2019-04-26-08-06-17-07](https://user-images.githubusercontent.com/50001414/56775618-71c91800-67fa-11e9-994a-6de1f9ab19dc.png)
![Screenshot_2019-04-26-08-06-23-25](https://user-images.githubusercontent.com/50001414/56775622-74c40880-67fa-11e9-826c-bcb819d9207f.png)
![Screenshot_2019-04-26-08-06-42-23](https://user-images.githubusercontent.com/50001414/56775625-77bef900-67fa-11e9-938b-dc1114517cda.png)

**Comment by MicroappsTeam** [comment]
Yes, great issues!

**Comment by Test123456789123456789Test** [comment]
Thx

**Comment by Test123456789123456789Test** [comment]
Kind of fixed
